### ISSUE TITLE
Package name?

### ISSUE THREAD

**Issue by vickyliin** [livingbio/gpt-fn#26]
是不是應該要把 import 的位置改成 `gpt_fn`? fn 這個名字實在是太 general 了

chatgpt 也覺得 gpt_fn 比較合理 XD
https://github.com/livingbio/gpt-fn#getting-started

**Comment by lucemia** [comment]
ok

我另外想要不要把 `Message` 改成 `MessageTemplate`

https://github.com/livingbio/gpt-fn/blob/1449523c2f5d62f3f26754945a558643606ac314/src/fn/prompt.py#L7

可以一起處理
