### ISSUE TITLE
support newest function call 

### ISSUE THREAD

**Issue by lucemia** [livingbio/gpt-fn#43]

**Comment by lucemia** [comment]
https://platform.openai.com/docs/guides/gpt/function-calling

**Comment by lucemia** [comment]
```
functions = [
    {
        "name": "get_current_weather",
        "description": "Get the current weather",
        "parameters": {
            "type": "object",
            "properties": {
                "location": {
                    "type": "string",
                    "description": "The city and state, e.g. San Francisco, CA",
                },
                "format": {
                    "type": "string",
                    "enum": ["celsius", "fahrenheit"],
                    "description": "The temperature unit to use. Infer this from the users location.",
                },
            },
            "required": ["location", "format"],
        },
    }
]

```

**Comment by vickyliin** [comment]
看起來可以參考
https://github.com/openai/openai-cookbook/blob/main/examples/How_to_call_functions_with_chat_models.ipynb

```python
def chat_completion_with_function_execution(messages, functions=None):
    """This function makes a ChatCompletion API call and if a function call is requested, executes the function"""
    try:
        response = chat_completion_request(messages, functions)
        full_message = response.json()["choices"][0]
        if full_message["finish_reason"] == "function_call":
            print(f"Function generation requested, calling function")
            return call_function(messages, full_message)
        else:
            print(f"Function not required, responding to user")
            return response.json()
    except Exception as e:
        print("Unable to generate ChatCompletion response")
        print(f"Exception: {e}")
        return response
```

**Comment by vickyliin** [comment]
實測 parameter 可以直接使用 pydantic 生出來的 schema

```python
class WeatherScripter(pydantic.BaseModel):
    location: str = pydantic.Field(
        description="The city and state, e.g. San Francisco, CA"
    )
    unit: Literal["celsius", "fahrenheit"] | None

    # Example dummy function hard coded to return the same weather
    # In production, this could be your backend API or an external API
    def script(location, unit="fahrenheit"):
        """Get the current weather in a given location"""
        return {
            "location": location,
            "temperature": "72",
            "unit": unit,
            "forecast": ["sunny", "windy"],
        }

WeatherScripter.schema()
```

```python
{'title': 'WeatherScripter',
 'type': 'object',
 'properties': {'location': {'title': 'Location',
   'description': 'The city and state, e.g. San Francisco, CA',
   'type': 'string'},
  'unit': {'title': 'Unit',
   'enum': ['celsius', 'fahrenheit'],
   'type': 'string'}},
 'required': ['location']}
```

**Comment by vickyliin** [comment]
...怎麼覺得他的 sample code 有問題，根本抓不到 arguments

```python
message, message.get('location')
```

(<OpenAIObject at 0x7f1374b3a750> JSON: {
   "role": "assistant",
   "content": null,
   "function_call": {
     "name": "get_current_weather",
     "arguments": "{\n  \"location\": \"Boston, MA\"\n}"
   }
 },
 None)

**Comment by lucemia** [comment]
> 實測 parameters 可以直接使用 pydantic 生出來的 schema
> 
> ```python
> class WeatherScripter(pydantic.BaseModel):
>     location: str = pydantic.Field(
>         description="The city and state, e.g. San Francisco, CA"
>     )
>     unit: Literal["celsius", "fahrenheit"] | None
> 
> WeatherScripter.schema()
> ```
> 
> ```python
> {'title': 'WeatherScripter',
>  'type': 'object',
>  'properties': {'location': {'title': 'Location',
>    'description': 'The city and state, e.g. San Francisco, CA',
>    'type': 'string'},
>   'unit': {'title': 'Unit',
>    'enum': ['celsius', 'fahrenheit'],
>    'type': 'string'}},
>  'required': ['location']}
> ```

早上試做有碰到一些問題，討論看看

```
def weather(location: str, unit: Literal["celsius", "fahrenheit"] ):
  ...
```

要動態轉成 Pydantic Model ，再轉乘 schema 嗎?
```
class WeatherScripter(pydantic.BaseModel):
    location: str = pydantic.Field(
        description="The city and state, e.g. San Francisco, CA"
    )
    unit: Literal["celsius", "fahrenheit"] | None

WeatherScripter.schema()
```

那 description 可能要 parse docstring ?

**Comment by vickyliin** [comment]
> 早上試做有碰到一些問題，討論看看
> 
> ```
> def weather(location: str, unit: Literal["celsius", "fahrenheit"] ):
>   ...
> ```
> 
> 要動態轉成 Pydantic Model ，再轉乘 schema 嗎?
> 

感覺 pydantic 有 pydantic.validate_argument 的話應該是可行的
不過我在想有沒有需要支援，畢竟他可以支援的 function argument 就跟 python 的 function argument 不是同一件事情，覺得可以限制要使用的 function 都只能傳一個 argument，然後標 pydantic model 就好

**Comment by vickyliin** [comment]
發現 @pydantic.validate_arguments 直接有設定 `wrapper_function.model`，這樣做成動態轉好像也滿簡單的

**Comment by lucemia** [comment]
可是不統一的話會和 ai_fn 有兩套標準，雖然他們的確是不同的用途
- ai_fn: given function definition, and input, generate output
- funcation call: given function definition, and goal, generate input  

目前 ai_fn 的 function 可以使用任何 python argument format (雖然不確定是不是都能夠正確 generate output)
然後 function call 的 function 只接受 pydantic object 作為 python argument .. 感覺怪

我在想說是不是統一成這兩個 function 都要求 function argument 能夠 convert 成 pydantic object (所以有些太花俏的樣式就不支援)，但是允許他寫成 `def weather(location: str, unit: Literal["celsius", "fahrenheit"] ):`

**Comment by vickyliin** [comment]
啊但確實還是有 description 的問題

**Comment by vickyliin** [comment]
啊可以這樣用
https://docs.pydantic.dev/latest/usage/validation_decorator/#using-field-to-describe-function-arguments

**Comment by lucemia** [comment]
> 啊 description 可以這樣用? https://docs.pydantic.dev/latest/usage/validation_decorator/#using-field-to-describe-function-arguments

我是想說 parse docstring  https://pypi.org/project/docstring-parser/ 
畢竟不能強迫都使用 pydantic 的 Field ?

**Comment by vickyliin** [comment]
> > 啊 description 可以這樣用? https://docs.pydantic.dev/latest/usage/validation_decorator/#using-field-to-describe-function-arguments
> 
> 我是想說 parse docstring https://pypi.org/project/docstring-parser/ 畢竟不能強迫都使用 pydantic 的 Field ?

docstring 也行，只是原本就有 pydantic 這個 dependency 在想是不是就可以直接用就好

不過剛剛實測 wrapper_function.model.schema() 轉出來有點醜，可能要測測看這樣 gpt 看不看得懂

**Comment by lucemia** [comment]
> > > 啊 description 可以這樣用? https://docs.pydantic.dev/latest/usage/validation_decorator/#using-field-to-describe-function-arguments
> > 
> > 
> > 我是想說 parse docstring https://pypi.org/project/docstring-parser/ 畢竟不能強迫都使用 pydantic 的 Field ?
> 
> docstring 也行，只是原本就有 pydantic 這個 dependency 在想是不是就可以直接用就好
> 
> 不過剛剛實測 wrapper_function.model.schema() 轉出來有點醜，可能要測測看這樣 gpt 看不看得懂

會有 `$definations` 對不對.. 不知道 gpt 吃的格式規範是什麼

**Comment by vickyliin** [comment]
> 會有 `$definations` 對不對.. 不知道 gpt 吃的格式規範是什麼

我還沒有做這麼複雜，只有給 weather 而已，長這樣

```json
{'title': 'Weather',
 'type': 'object',
 'properties': {'location': {'title': 'Location', 'type': 'string'},
  'v__duplicate_kwargs': {'title': 'V  Duplicate Kwargs',
   'type': 'array',
   'items': {'type': 'string'}},
  'unit': {'title': 'Unit',
   'enum': ['celsius', 'fahrenheit'],
   'type': 'string'},
  'args': {'title': 'Args', 'type': 'array', 'items': {}},
  'kwargs': {'title': 'Kwargs', 'type': 'object'}},
 'required': ['location', 'unit'],
 'additionalProperties': False}
```

不過如果有 reference 到別的 model, nested 的狀況下應該會有 `$definition` 沒錯

**Comment by lucemia** [comment]
> > 會有 `$definations` 對不對.. 不知道 gpt 吃的格式規範是什麼
> 
> 我還沒有做這麼複雜，只有給 weather 而已，長這樣
> 
> ```python
> {'title': 'Weather',
>  'type': 'object',
>  'properties': {'location': {'title': 'Location', 'type': 'string'},
>   'v__duplicate_kwargs': {'title': 'V  Duplicate Kwargs',
>    'type': 'array',
>    'items': {'type': 'string'}},
>   'unit': {'title': 'Unit',
>    'enum': ['celsius', 'fahrenheit'],
>    'type': 'string'},
>   'args': {'title': 'Args', 'type': 'array', 'items': {}},
>   'kwargs': {'title': 'Kwargs', 'type': 'object'}},
>  'required': ['location', 'unit'],
>  'additionalProperties': False}
> ```
> 
> 不過如果有 reference 到別的 model, nested 的狀況下應該會有 `$definition` 沒錯

可以給我生成這段的 sample code 嗎? 我研究一下


`$ref` & `$definition` 如果 openai 不支援，可以這樣子修
https://github.com/pydantic/pydantic/issues/889

**Comment by vickyliin** [comment]
在 studio 隨便找了一個看起來滿複雜的來測

```
from story.theme.implementations.article.layouts import ArticleLayout


functions = [
    {
        "name": "test_complicated_parameters",
        "description": "a debug function to check if the assistant can call function with complicated parameters",
        "parameters": ArticleLayout.schema()
    }
]

response = openai.ChatCompletion.create(
    model="gpt-3.5-turbo-0613",
    messages=[{"role": "user", "content": "Use test_complicated_parameters with valid parameters"}],
    functions=functions,
    function_call="auto",
)

args = response.choices[0].message.function_call.arguments
print(args)
```

$definition 的部分應該沒問題

**Comment by vickyliin** [comment]
好像也滿正常的

```python
from typing import Any, Literal
import openai
import pydantic


@pydantic.validate_arguments
def get_current_weather(
    location: str, unit: Literal["celsius", "fahrenheit"] = "fahrenheit"
) -> dict[str, Any]:
    """ "Get the current weather in a given location"""

    return {
        "location": location,
        "temperature": "72",
        "unit": unit,
        "forecast": ["sunny", "windy"],
    }


functions = [
    {
        "name": get_current_weather.__name__,
        "description": get_current_weather.__doc__,
        "parameters": get_current_weather.model.schema(),
    }
]


response = openai.ChatCompletion.create(
    model="gpt-3.5-turbo-0613",
    messages=[
        {
            "role": "user",
            "content": "What's the weather in San Francisco?",
        }
    ],
    functions=functions,
    function_call="auto",
)

args = response.choices[0].message.function_call.arguments
print(args)

get_current_weather.model.parse_raw(args)
```

**Comment by vickyliin** [comment]
可以直接使用 ValidatedFunction, 呼叫就跑 `vd.execute(vd.model.parse_raw(args))`

```python
import openai
from typing import Any, Literal
from pydantic.decorator import ValidatedFunction


def get_current_weather(
    *locations: str, unit: Literal["celsius", "fahrenheit"]
) -> dict[str, Any]:
    """ "Get the current weather in a given location"""

    return [
        {
            "location": location,
            "temperature": "72",
            "forecast": ["sunny", "windy"],
        }
        for location in locations
    ]

vd = ValidatedFunction(get_current_weather, None)

functions = [
    {
        "name": get_current_weather.__name__,
        "description": get_current_weather.__doc__,
        "parameters": vd.model.schema(),
    }
]

response = openai.ChatCompletion.create(
    model="gpt-3.5-turbo-0613",
    messages=[
        {
            "role": "user",
            "content": "What's the weather in San Francisco and New York?",
        }
    ],
    functions=functions,
    function_call="auto",
)

args = response.choices[0].message.function_call.arguments
print(args)

vd.execute(vd.model.parse_raw(args))
```

**Comment by lucemia** [comment]
看起來東西齊了! 可以 implement 了~

**Comment by lucemia** [comment]
@vickyliin 想要 implement 嗎? 或是等我把 genv-fs 搞定再來 implement?

**Comment by vickyliin** [comment]
沒有測過這功能實際使用情形，所以還沒有很確定要做怎樣的包裝比較通用
